//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCNX.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class COUNTRY_FLAG
    {
        [Key]
        public int SRNO { get; set; }
        public string NAME { get; set; }
        public string FLAG { get; set; }
        public string CODE { get; set; }
        public string ISO_CODE { get; set; }
        public Nullable<int> status { get; set; }
    }
}
