//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCNX.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Singlelegincomechart
    {
        [Key]
        public int id { get; set; }
        public int stage { get; set; }
        public decimal team { get; set; }
        public decimal teamshow { get; set; }
        public decimal direct { get; set; }
        public decimal single_Leg_Income { get; set; }
        public decimal sponcer_Income { get; set; }
        public decimal dailyincome { get; set; }
        public decimal days { get; set; }
        public decimal reentry { get; set; }
        public decimal nonworking { get; set; }
    }
}
