//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCNX.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class tblCmbDetail
    {
        [Key]
        public int id { get; set; }
        public string keytype { get; set; }
        public string keyvalue { get; set; }
        public string keyvalue2 { get; set; }
        public string keyvalue3 { get; set; }
        public string type { get; set; }
        public bool isactive { get; set; }
    }
}
