//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCNX.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class tblgetlink
    {
        [Key]
        public int id { get; set; }
        public string mid { get; set; }
        public string mname { get; set; }
        public int linkbalance { get; set; }
        public int givecnt { get; set; }
        public int spcnt { get; set; }
        public string partner_status { get; set; }
        public System.DateTime edate { get; set; }
        public int sendstatus { get; set; }
    }
}
