//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCNX.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class tblincome
    {
        [Key]
        public int id { get; set; }
        public string mid { get; set; }
        public System.DateTime edate { get; set; }
        public decimal growth { get; set; }
        public decimal level { get; set; }
        public decimal sponcer { get; set; }
        public decimal bidding { get; set; }
        public decimal recharge { get; set; }
        public decimal repurchase { get; set; }
        public decimal growthwd { get; set; }
        public decimal levelwd { get; set; }
        public decimal sponcerwd { get; set; }
        public decimal biddingwd { get; set; }
        public decimal rechargewd { get; set; }
        public decimal repurchasewd { get; set; }
        public decimal linkbalance { get; set; }
        public decimal linkbalance2 { get; set; }
        public decimal withdraw { get; set; }
        public decimal withdrawwd { get; set; }
    }
}
