//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCNX.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class tbllinkdetail
    {
        [Key]
        public int id { get; set; }
        public string mid { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<int> givecnt { get; set; }
        public Nullable<int> takecnt { get; set; }
        public Nullable<int> profitcnt { get; set; }
        public Nullable<int> linkSend { get; set; }
        public Nullable<int> gtStatus { get; set; }
        public decimal pamount { get; set; }
        public decimal linkbalance { get; set; }
        public decimal linkbalance2 { get; set; }
        public System.DateTime tdate { get; set; }
        public decimal rejectwd { get; set; }
    }
}
