//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCNX.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class tblpayout
    {
        [Key]
        public int id { get; set; }
        public string mid { get; set; }
        public decimal pv { get; set; }
        public System.DateTime edate { get; set; }
        public int status { get; set; }
        public decimal level { get; set; }
        public decimal sponcer { get; set; }
        public decimal growth { get; set; }
        public decimal bidding { get; set; }
        public decimal recharge { get; set; }
        public decimal repurchase { get; set; }
        public decimal servicecharge { get; set; }
        public decimal admincharge { get; set; }
        public decimal payout { get; set; }
        public decimal final_payout { get; set; }
        public string remark { get; set; }
        public int type { get; set; }
        public int cycle { get; set; }
    }
}
