//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCNX.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class tblpinhistory
    {
        [Key]
        public int id { get; set; }
        public System.DateTime edate { get; set; }
        public string givemid { get; set; }
        public string takemid { get; set; }
        public string pin { get; set; }
        public string status { get; set; }
        public int pinType { get; set; }
        public decimal pinamt { get; set; }
    }
}
