//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCNX.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbltranshistory
    {
        [Key]
        public int tid { get; set; }
        public System.DateTime edate { get; set; }
        public string givemid { get; set; }
        public string takemid { get; set; }
        public decimal tamount { get; set; }
        public Nullable<decimal> deduction { get; set; }
        public Nullable<decimal> final_amount { get; set; }
        public int approvedstatus { get; set; }
        public System.DateTime approved_date { get; set; }
        public string txthash { get; set; }
        public string status { get; set; }
        public string remark { get; set; }
        public string payment_id { get; set; }
        public string orderid { get; set; }
        public string order_description { get; set; }
        public string currency { get; set; }
        public int ttype { get; set; }
        public int bid { get; set; }
        public int type { get; set; }
        public string imgname { get; set; }
        public string ipaddress { get; set; }
        public string devicename { get; set; }
        public string location { get; set; }
        public string invoice_id { get; set; }
    }
}
